issue#152 : 봉선호 : studygroup : 그룹 제목으로 검색
seoyeonDev/Su-p pull request #162
Opened 2024-06-04 00:20 UTC by Ohnus

## 해결하려는 문제가 무엇인가요?
> '#이슈번호 문제내용' 과 같은 형식으로 작성해주세요.
* #152 
> 
<br/>

## 어떻게 해결했나요?
> 이번 PR의 작업 내용을 간략히 설명해주세요. (이미지 및 파일 첨부 (선택))
* 제목으로 그룹 리스트 검색하기
* like로 검색

<br/>

## 리뷰 요구사항 (선택)
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요. 
*

2024-06-05 11:32 UTC, haeburney approved these changes
수고하셨습니다!

2024-06-05 11:40 UTC, seoyeonDev requested changes

2024-06-05 11:40 UTC, seoyeonDev commented on Backend/src/main/java/com/example/studyproject/studygroup/StudyGroupController.java
> +		// 리턴 변수 클라이언트단 작업하면서 수정
우리 역할 배정 특성 상 누가 클라이언트단(프론트를 의미하는거겠지요?) 맡을 지 모릅니다. 
때문에 Bug 로 남겨놓고 Usecase 완료 시 해당 부분 바로 작업하거나, 임시로 리턴값을 설정하는게 좋을 것 같습니다.

2024-06-09 07:53 UTC, seoyeonDev approved these changes

2024-06-09 15:11 UTC, merged