issue#172 : 봉선호 : studylogs : 스터디로그 상세 조회
seoyeonDev/Su-p pull request #173
Opened 2024-06-09 07:29 UTC by Ohnus

## 해결하려는 문제가 무엇인가요?
> '#이슈번호 문제내용' 과 같은 형식으로 작성해주세요.
* #172 
> 
<br/>

## 어떻게 해결했나요?
> 이번 PR의 작업 내용을 간략히 설명해주세요. (이미지 및 파일 첨부 (선택))
* 스터디로그 vo 상세 조회

<br/>

## 리뷰 요구사항 (선택)
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요. 
*

2024-06-10 07:50 UTC, haeburney approved these changes

2024-06-11 12:20 UTC, seoyeonDev requested changes

2024-06-11 12:20 UTC, seoyeonDev commented on Backend/src/main/java/com/example/studyproject/studylogs/StudyLogs.java
> +    public StudyLogs() {
해당부분 로컬에서 main 브랜치 update 마다 주석처리해야해서, 이 부분을 주석처리 or @NoArgsConstructor 어노테이션 부분을 주석처리해서 올려주세요. 어노테이션 부분을 주석처리하면 될 것 같습니다.

2024-06-11 13:28 UTC, Ohnus commented on Backend/src/main/java/com/example/studyproject/studylogs/StudyLogs.java
> +    public StudyLogs() {
우선 롬복 관련 어노테이션을 냅두고 아래에 직접 수동으로 생성한 생성자와 게터, 세터를 주석처리했습니다.
해당 vo외에 다른 vo들도 같은 방식으로 주석처리해서 새로운 브랜치로 pr해놓고 제가 작업할 때 주석 풀고 작업하는게 나을 거 같습니다.

2024-06-12 05:47 UTC, seoyeonDev approved these changes

2024-06-23 03:01 UTC, merged