#180 : 김혜원 : studylogs 수정 : studylogs 제목, 내용, update 수정
seoyeonDev/Su-p pull request #184
Opened 2024-06-10 13:47 UTC by haeburney

## 해결하려는 문제가 무엇인가요?
> '#이슈번호 문제내용' 과 같은 형식으로 작성해주세요.
* #180  studylogs 수정
> 
<br/>

## 어떻게 해결했나요?
> 이번 PR의 작업 내용을 간략히 설명해주세요. (이미지 및 파일 첨부 (선택))
* studylogs 제목, 내용, 수정일 수정

<br/>

## 리뷰 요구사항 (선택)
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요. 
*

2024-06-11 12:45 UTC, seoyeonDev requested changes

2024-06-11 12:45 UTC, seoyeonDev commented on Backend/src/main/java/com/example/studyproject/studylogs/StudyLogsController.java
> +    @PutMapping("/update/{post_id}")
메서드 설명 빠졌습니다.

2024-06-11 12:45 UTC, seoyeonDev commented on Backend/src/main/java/com/example/studyproject/studylogs/StudyLogsService.java
> +    public void updateStudyLogs(StudyLogs vo){
메서드 주석 studylogs_sql.xml 파일이랑 일치시키는게 가독성이 더 좋을 것 같습니다.

2024-06-11 12:45 UTC, seoyeonDev commented on Backend/src/main/java/com/example/studyproject/studylogs/StudyLogsDao.java
> +    // 업데이트
메서드 주석명 통일 부탁드립니다.

2024-06-11 13:37 UTC, Ohnus approved these changes

2024-06-16 14:47 UTC, seoyeonDev approved these changes

2024-06-24 01:23 UTC, merged