#254 : 김혜원 : member 회원가입 10분 안내 : member 회원가입 이메일 10분 안내
seoyeonDev/Su-p pull request #264
Opened 2024-07-15 12:04 UTC by haeburney

## 해결하려는 문제가 무엇인가요?
> '#이슈번호 문제내용' 과 같은 형식으로 작성해주세요.
* #254 이메일 10분 카운트
> 버그 수정일 시 빠른 확인을 위해 Label > Bugs 선택해주세요.
<br/>

## 어떻게 해결했나요?
> 이번 PR의 작업 내용을 간략히 설명해주세요. (이미지 및 파일 첨부 (선택))
* 메일 수신에 성공하면 10분 카운트를 진행하였습니다. 

<br/>

## 리뷰 요구사항 (선택)
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요. 
*

2024-07-16 08:08 UTC, seoyeonDev requested changes
10분 제한 뿐만 아니라 다른 수정사항도 있는 듯해 보이는데, 맞으면 PR 상세 메세지 추가 부탁드립니다 !@

2024-07-16 08:08 UTC, seoyeonDev commented on Frontend/src/pages/member/Join.js
> +    }
이건 회원가입 시 등록하는 이미지인가요?

2024-07-17 05:37 UTC, haeburney commented on Frontend/src/pages/member/Join.js
> +    }
네. 회원가입할 때 등록하는 이미지인데, 이 부분은 파일 선택을 했을시 미리보기를 제공하기 위해서 만들어진 로직입니다!

2024-07-17 05:38 UTC, haeburney commented
> 10분 제한 뿐만 아니라 다른 수정사항도 있는 듯해 보이는데, 맞으면 PR 상세 메세지 추가 부탁드립니다 !@

추가 했습니다~!!!!

2024-07-17 07:50 UTC, seoyeonDev approved these changes

2024-07-17 11:44 UTC, Ohnus approved these changes

2024-07-17 11:56 UTC, merged