issue275 : 봉선호 : member : BE, FE 마이페이지 접속 위한 비밀번호 검증 페이지 추가
seoyeonDev/Su-p pull request #278
Opened 2024-07-21 10:03 UTC by Ohnus

## 해결하려는 문제가 무엇인가요?
> '#이슈번호 문제내용' 과 같은 형식으로 작성해주세요.
* #277 
> 버그 수정일 시 빠른 확인을 위해 Label > Bugs 선택해주세요.
<br/>

## 어떻게 해결했나요?
> 이번 PR의 작업 내용을 간략히 설명해주세요. (이미지 및 파일 첨부 (선택))
* BE, FE 마이페이지 접속 위한 비밀번호 검증 페이지 추가

<br/>

## 리뷰 요구사항 (선택)
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요. 
*

2024-07-24 06:30 UTC, haeburney approved these changes
수고하셨습니다!

2024-07-26 08:17 UTC, seoyeonDev requested changes

2024-07-26 08:17 UTC, seoyeonDev commented on Backend/src/main/java/com/example/studyproject/member/MemberController.java
> +	public boolean inputPassword(@RequestParam String user_id, @RequestParam String password) {
requestparam 으로 비밀번호를 받아오는건 보안적으로 문제가 있을 것 같습니다. body 처리가 더 나을 것 같습니다.

2024-07-28 09:14 UTC, Ohnus commented on Backend/src/main/java/com/example/studyproject/member/MemberController.java
> +	public boolean inputPassword(@RequestParam String user_id, @RequestParam String password) {
컨트롤러, js 둘 다 post, body로 수정완료했슴니다

2024-07-28 14:00 UTC, seoyeonDev approved these changes

2024-07-28 14:01 UTC, merged