20240415 Group 추가 및 회원 탈퇴 기능
seoyeonDev/Su-p pull request #40
Opened 2024-04-15 14:18 UTC by haeburney

## 해결하려는 문제가 무엇인가요?
> '#이슈번호 문제내용' 과 같은 형식으로 작성해주세요.
* #39 
> 
<br/>

## 어떻게 해결했나요?
> 이번 PR의 작업 내용을 간략히 설명해주세요. (이미지 및 파일 첨부 (선택))
* 회원탈퇴 기능을 만들었다.
* 반환값은 int로 탈퇴한 수가 1이라면 잘 된것, 0이라면 탈퇴가 안 된것
* 으로 만들어봤습니다.

<br/>

## 리뷰 요구사항 (선택)
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요. 
*

2024-04-15 21:49 UTC, seoyeonDev requested changes
그룹이랑 회원이랑 PR 분리 필요

2024-04-16 08:06 UTC, closed without merging

2024-04-16 12:44 UTC, seoyeonDev commented on Backend/src/main/java/com/example/studyproject/group/Group.java
> +    private String desc;        // 스터디 소개
SQL 에서 컬럼명을 desc 사용이 가능한지 확인이 필요할 것 같습니다.

2024-04-16 12:45 UTC, Ohnus commented on Backend/src/main/java/com/example/studyproject/group/Group.java
> +    private String desc;        // 스터디 소개
// 쿼리 오류로 desc 대신 group_desc로 수정

2024-04-16 12:45 UTC, Ohnus reviewed
수고하셨습니다.